### ISSUE TITLE
panic while merging in unit test

### ISSUE THREAD

**Issue by mschoch** [blugelabs/bluge#119]
```
 panic: runtime error: slice bounds out of range [:1153] with capacity 1152

goroutine 95 [running]:
github.com/blugelabs/ice/v2.(*Segment).copyStoredDocs(0xc000b40780, 0x200, 0xc000fc0000, 0x7d0, 0x7d0, 0xc000fad3f0, 0x0, 0x1)
	C:/Users/runneradmin/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.0/merge.go:787 +0x745
github.com/blugelabs/ice/v2.mergeStoredAndRemap(0xc000621f40, 0x3, 0x3, 0xc000621f20, 0x3, 0x3, 0xc0006b88d0, 0xc0006b88a0, 0x3, 0x3, ...)
	C:/Users/runneradmin/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.0/merge.go:659 +0x853
github.com/blugelabs/ice/v2.mergeToWriter(0xc000621f40, 0x3, 0x3, 0xc000621f20, 0x3, 0x3, 0x401, 0xc000621f60, 0xc000798fc0, 0xc000621f40, ...)
	C:/Users/runneradmin/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.0/merge.go:130 +0x21c
github.com/blugelabs/ice/v2.mergeSegmentBasesWriter(0xc000621f40, 0x3, 0x3, 0xc000621f20, 0x3, 0x3, 0x9c2580, 0xc0009fe300, 0x401, 0xc000798fc0, ...)
	C:/Users/runneradmin/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.0/merge.go:96 +0x15a
github.com/blugelabs/ice/v2.merge(0xc0006b8870, 0x3, 0x3, 0xc000621f20, 0x3, 0x3, 0x9c2580, 0xc0009fe300, 0xc000798fc0, 0x0, ...)
	C:/Users/runneradmin/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.0/merge.go:85 +0x1d4
github.com/blugelabs/ice/v2.(*Merger).WriteTo(0xc000cd4910, 0x9c2cc0, 0xc0009d8110, 0xc000798fc0, 0x9c61e0, 0xc000044950, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/blugelabs/ice/v2@v2.0.0/merge.go:48 +0x191
github.com/blugelabs/bluge/index.(*FileSystemDirectory).Persist(0xc0000ba780, 0x943751, 0x4, 0xd, 0x1d124eabf58, 0xc000cd4910, 0xc000798fc0, 0x9c4e60, 0xc000cd4910)
	D:/a/bluge/bluge/index/directory_fs.go:125 +0x2d5
github.com/blugelabs/bluge/index.(*Writer).merge(0xc0002f4480, 0xc0006b8870, 0x3, 0x3, 0xc000621f20, 0x3, 0x3, 0xd, 0x3, 0xc0009fe100, ...)
	D:/a/bluge/bluge/index/merge.go:368 +0x22b
github.com/blugelabs/bluge/index.(*Writer).executeMergeTask(0xc0002f4480, 0xc0007990e0, 0xc000621f00, 0xc000cd48c0, 0xc000621ea0)
	D:/a/bluge/bluge/index/merge.go:144 +0x88b
github.com/blugelabs/bluge/index.(*Writer).planMergeAtSnapshot(0xc0002f4480, 0xc0007990e0, 0xc0000fa980, 0xa, 0x4c4b40, 0x4024000000000000, 0xa, 0x7d0, 0x4000000000000000, 0x0, ...)
	D:/a/bluge/bluge/index/merge.go:118 +0x47c
github.com/blugelabs/bluge/index.(*Writer).mergerLoop(0xc0002f4480, 0xc0007990e0, 0xc000895380)
	D:/a/bluge/bluge/index/merge.go:56 +0x4e5
created by github.com/blugelabs/bluge/index.OpenWriter
	D:/a/bluge/bluge/index/writer.go:131 +0xf8e
FAIL	github.com/blugelabs/bluge	1.570s
```

**Comment by mschoch** [comment]
I was able to reproduce this locally, the key is include the race detector:

```
go test -race -v -count=20
```

**Comment by mschoch** [comment]
So, it looks to me like this is just a general issue with the way we coded access to these slices.

In some cases we're at some random spot in the slice, and are expecting a varint.  So we try to access from `[pos:pos+binary.MaxVarintLen64]` and this is just generally unsafe if you might be getting to the end of the buffer (actually varint took 1 byte, so slice ends before accessed range)

**Comment by mschoch** [comment]
fixed by https://github.com/blugelabs/bluge/pull/120
