### ISSUE TITLE
Concurrently close writer panic

### ISSUE THREAD

**Issue by KaniuBillows** [blugelabs/bluge#140]
Here is my test code, I open a writer and write a document, then close it concurrently.
```
func TestWriterClose(t *testing.T) {
	config := DefaultConfig("./example")
	config.indexConfig.PersisterNapTimeMSec = 1000
	writer, err := OpenWriter(config)
	if err != nil {
		t.FailNow()
	}

	doc := NewDocument("example").
		AddField(NewTextField("name", "bluge"))

	wg := sync.WaitGroup{}
	wg.Add(1)
	go func() {
		writer.Close()
		wg.Done()
	}()
	err = writer.Update(doc.ID(), doc)
	if err != nil {
		if !errors.Is(err, segment.ErrClosed) {
			t.Error(err)
			t.FailNow()
		}
		t.Log("index closed")
	}
	wg.Wait()
}
```

I got this panic info:

```panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10285d808]

goroutine 6 [running]:
testing.tRunner.func1.2({0x102957f00, 0x102b3a5c0})
        /usr/local/go/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x384
panic({0x102957f00, 0x102b3a5c0})
        /usr/local/go/src/runtime/panic.go:884 +0x204
github.com/blugelabs/bluge/index.(*Snapshot).decRef(0x140001a98b8?)
        /Users/kaniu/dev/bluge/index/snapshot.go:72 +0x18
github.com/blugelabs/bluge/index.(*Snapshot).Close(...)
        /Users/kaniu/dev/bluge/index/snapshot.go:89
github.com/blugelabs/bluge/index.(*Writer).prepareSegment.func1()
        /Users/kaniu/dev/bluge/index/writer.go:314 +0x24
panic({0x102957f00, 0x102b3a5c0})
        /usr/local/go/src/runtime/panic.go:884 +0x204
github.com/blugelabs/bluge/index.(*Writer).prepareSegment(0x1400004ed80, 0x14000079350, {0x14000061450?, 0x1, 0x1}, 0x0, 0x0)
        /Users/kaniu/dev/bluge/index/writer.go:320 +0x1e8
github.com/blugelabs/bluge/index.(*Writer).Batch(0x1400004ed80, 0x140001a9c10)
        /Users/kaniu/dev/bluge/index/writer.go:275 +0x314
github.com/blugelabs/bluge.(*Writer).Batch(...)
        /Users/kaniu/dev/bluge/writer.go:63
github.com/blugelabs/bluge.(*Writer).Update(0x14000000640, {0x10299e3f0?, 0x14000061430}, {0x10299dec8?, 0x140002f4768})
        /Users/kaniu/dev/bluge/writer.go:53 +0x130
github.com/blugelabs/bluge.TestWriterClose(0x14000003a00)
        /Users/kaniu/dev/bluge/index_test.go:1841 +0x41c
testing.tRunner(0x14000003a00, 0x10299c1b8)
        /usr/local/go/src/testing/testing.go:1576 +0x10c
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x368
FAIL    github.com/blugelabs/bluge      0.537s
```
And the problem should be here:
https://github.com/blugelabs/bluge/blob/57414197005148539c5dc5db8ab581594969df79/index/writer.go#L307C1-L317C3
the current snapshot we got is nil, so it panic.
I think we should do more check right?

just like index/wirter.go 310:
```
// optimistically prepare obsoletes outside of rootLock
	root := s.currentSnapshot()
	defer func() {
		if root != nil {
			_ = root.Close()
		}
	}()
	if root == nil {
		return segment.ErrClosed
	}
```

**Comment by gaby** [comment]
@mschoch Would it be possible to get a fix for this? Not sure if you plan to continue this project. Thanks!
